# Generated by Django 4.0.6 on 2022-09-04 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(choices=[('aws', 'Awmazon Web Service'), ('gcp', 'Google Cloud Platform'), ('scw', 'Scaleway Cloud')], max_length=50)),
                ('type', models.CharField(choices=[('compute', 'Compute'), ('database', 'Database'), ('storage', 'Storage')], max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('extra', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tfmaker_service',
            },
        ),
    ]
