# Generated by Django 4.0.6 on 2022-10-05 16:14

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tf_key',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='extra',
            field=django_jsonform.models.fields.JSONField(default=list),
        ),
    ]
